export type Distrito = {
  name: string
  deliveryFee: number // en colones
  barrios: string[]
}

// Solo los 4 distritos activos para delivery
export const DISTRITOS: Distrito[] = [
  {
    name: 'San Isidro de El General',
    deliveryFee: 1000,
    barrios: [
      'Centro',
      'Barrio Corazón de Jesús',
      'Barrio El Llano',
      'Barrio La Colina',
      'Barrio Los Ángeles',
      'Barrio Fátima',
      'Barrio San Martín',
      'Barrio Cristo Rey',
      'Barrio La Mora',
      'Barrio El Jardín',
      'Barrio Las Américas',
      'Barrio Sagrada Familia',
      'Barrio San Francisco',
      'Barrio La Paz',
      'Barrio San Luis',
      'Barrio El Carmen',
      'Barrio La Esperanza',
      'Barrio San Antonio',
      'Barrio El Progreso',
      'Barrio La Victoria',
      'Barrio Juan Pablo II',
      'Barrio Loma de Cocorí',
      'Barrio Pavones',
      'Barrio Los Ángeles Norte',
      'Barrio El Roble',
      'Barrio La Granja',
      'Barrio San Bosco',
      'Barrio El Estadio',
      'Barrio Los Pinos',
      'Barrio La Ribera',
      'Barrio El Porvenir',
      'Barrio Las Brisas',
      'Barrio La Unión',
      'Barrio San Jorge',
      'Barrio El Molino',
      'Urbanización Los Almendros',
      'Urbanización El Roble',
      'Urbanización La Colina',
      'Urbanización Los Pinos',
      'Residencial Los Almendros',
      'Residencial El Jardín',
    ],
  },
  {
    name: 'Daniel Flores',
    deliveryFee: 1500,
    barrios: [
      'Centro Daniel Flores',
      'Barrio El Progreso',
      'Barrio La Unión',
      'Barrio San Antonio',
      'Barrio El Carmen',
      'Barrio Las Brisas',
      'Barrio La Victoria',
      'Barrio El Porvenir',
      'Barrio San José',
      'Barrio La Esperanza',
      'Barrio El Bosque',
      'Barrio San Rafael',
      'Barrio La Colonia',
      'Barrio Los Ángeles',
      'Barrio El Palmar',
      'Barrio La Ribera',
      'Barrio San Marcos',
      'Barrio El Cruce',
      'Barrio La Loma',
      'Barrio San Juan',
      'Barrio El Llano',
      'Barrio La Cruz',
      'Barrio San Miguel',
      'Barrio La Cuesta',
      'Barrio El Río',
      'Barrio San Rafael Norte',
      'Urbanización Los Laureles',
      'Residencial Las Palmas',
    ],
  },
  {
    name: 'El General',
    deliveryFee: 2000,
    barrios: [
      'Centro El General',
      'Barrio La Esperanza',
      'Barrio San Juan',
      'Barrio El Bosque',
      'Barrio La Montaña',
      'Barrio El Progreso',
      'Barrio San Antonio',
      'Barrio La Unión',
      'Barrio El Carmen',
      'Barrio Las Brisas',
      'Barrio La Victoria',
      'Barrio El Porvenir',
      'Barrio San José',
      'Barrio La Colonia',
    ],
  },
  {
    name: 'Rivas',
    deliveryFee: 2500,
    barrios: [
      'Centro Rivas',
      'Barrio La Palma',
      'Barrio El Río',
      'Barrio San Rafael',
      'Barrio La Loma',
      'Barrio El Progreso',
      'Barrio San Antonio',
      'Barrio La Unión',
      'Barrio El Carmen',
      'Barrio Las Brisas',
      'Barrio La Victoria',
      'Barrio El Porvenir',
      'Barrio San José',
      'Barrio La Esperanza',
    ],
  },
]
